/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import Entidades.*;
import Sistema.Configuracion;
import Listas.*;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.lang.Exception;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FrameGestionEquipos extends javax.swing.JFrame {

    /**
     * Creates new form frmListaDeEquipos
     */
    public FrameGestionEquipos() {
        initComponents();
        cargarTabla();
         
        
        if(Configuracion.usuario.getNombre().equalsIgnoreCase("Administrador")){
            this.btnAgregar.setEnabled(true);
            this.btnEliminar.setEnabled(true);
            this.btnModificar.setEnabled(true);
            this.btnRegresar.setEnabled(true);
            
        }else{
            
            this.btnAgregar.setEnabled(false);
            this.btnEliminar.setEnabled(false);
            this.btnModificar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCentral1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEquipos = new javax.swing.JTable();
        panCentral2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaJugadoresDelEquipo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblEquipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panCentral1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setEnabled(false);

        tablaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEquiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEquipos);

        javax.swing.GroupLayout panCentral1Layout = new javax.swing.GroupLayout(panCentral1);
        panCentral1.setLayout(panCentral1Layout);
        panCentral1Layout.setHorizontalGroup(
            panCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCentral1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panCentral1Layout.setVerticalGroup(
            panCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCentral1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panCentral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 200));

        panCentral2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setEnabled(false);

        tablaJugadoresDelEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaJugadoresDelEquipo);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Jugadores de:");

        lblEquipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEquipo.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout panCentral2Layout = new javax.swing.GroupLayout(panCentral2);
        panCentral2.setLayout(panCentral2Layout);
        panCentral2Layout.setHorizontalGroup(
            panCentral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCentral2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCentral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panCentral2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panCentral2Layout.setVerticalGroup(
            panCentral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCentral2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(panCentral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(panCentral2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 890, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CLUBES DE LA LIGA 1 ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 270, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, -1, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpg"))); // NOI18N
        lblFondo.setText("jLabel3");
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        FrameEquipo frm = new FrameEquipo();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        int fila=0;
        int columna=0;
        String posicion="";
        Equipo equipo;
        
      try{
          
       fila=this.tablaEquipos.getSelectedRow();
        
       posicion= (String)this.tablaEquipos.getValueAt(fila,columna);
       
       equipo=Configuracion.equipos.getEquipos().get(Integer.parseInt(posicion)-1);
       
       FrameEquipo frm = new FrameEquipo(equipo);
       frm.setLocationRelativeTo(null);
       frm.setVisible(true);
       this.dispose();
       
          
      }catch(IndexOutOfBoundsException e){
        JOptionPane.showMessageDialog(this, "ERROR EN ELEGIR LA FILA: "+posicion);
      }  
       
       
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
        
        this.dispose();
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
          try{
        int i = this.tablaEquipos.getSelectedRow();
        Equipo e = Configuracion.equipos.getEquipos().get(i);
        if(e != null){
            Configuracion.equipos.eliminar(e);
        }else{
            JOptionPane.showMessageDialog(this,"Equipo no encontrado");
        }
       
        DefaultTableModel tabla;
        tabla = new DefaultTableModel(Configuracion.equipos.getMatrizEquipos(),Configuracion.equipos.getTitulos());
        this.tablaEquipos.setModel(tabla);   
        
        }catch(IndexOutOfBoundsException p){
            JOptionPane.showMessageDialog(this, "FILA NO SELECCIONADA");
        }        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
    }//GEN-LAST:event_formKeyPressed

    private void tablaEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEquiposMouseClicked
        // TODO add your handling code here:
        try {
            int columna=0;
            int fila=0;
            String nombre="";
             fila = this.tablaEquipos.getSelectedRow();
            
        DefaultTableModel table = new DefaultTableModel(Configuracion.equipos.getEquipos().get(fila).getMatrizJugadores(),
        Configuracion.equipos.getEquipos().get(fila).getTitulosJugadores());
        this.tablaJugadoresDelEquipo.setModel(table);
        this.lblEquipo.setText(Configuracion.equipos.getEquipos().get(fila).getNombre());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:"+e);
        }
        
    }//GEN-LAST:event_tablaEquiposMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGestionEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPanel panCentral1;
    private javax.swing.JPanel panCentral2;
    private javax.swing.JTable tablaEquipos;
    private javax.swing.JTable tablaJugadoresDelEquipo;
    // End of variables declaration//GEN-END:variables

private void cargarTabla(){
    
    DefaultTableModel table = new DefaultTableModel(Configuracion.equipos.getMatrizEquipos(),
        Configuracion.equipos.getTitulos());
        this.tablaEquipos.setModel(table);
        this.tablaEquipos.getColumnModel().getColumn(0).setPreferredWidth(10); 
    
}        
        
}
