/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Sistema.Configuracion;
import Calendario.Calendario;
import Entidades.Convocado;
import Entidades.Encuentro;
import Entidades.Equipo;
import Entidades.Fecha;
import Entidades.Jugador;
import Entidades.Persona;
import Entidades.Plantel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FrameGestionJornadas extends javax.swing.JFrame {

    /**
     * Creates new form FrameGestionJornadas
     */
    
    Calendario calendario=new Calendario(Configuracion.equipos.cantidadDeEquipos());
   // boolean estadosJornadas;
   
    
    
    
    
    
    public FrameGestionJornadas() {
        initComponents();
        this.cargarcomboBox();
        this.tblJornadas.setEnabled(false);
        
        this.cbJornadas2.setEnabled(false);
        if(Configuracion.fechas.getFechas().size()==0){
          this.crearJornadas();
         // this.guardarJornadas();
          
          JOptionPane.showMessageDialog(this, "Fechas creadas");
        }else{
            JOptionPane.showMessageDialog(this, "cargando Fechas");
        }
            
       
        
    }
    
    
    public FrameGestionJornadas(int jornada) {
        initComponents();
        this.cargarcomboBox();
      //  this.cargarTablaIda(jornada);
      /*  this.cbJornadas2.setEnabled(false);
        
       this.tblJornadas.setValueAt((String)equipo1, this.obtenerFila(nombre), 1);
        this.tblJornadas.setValueAt((String)equipo2, this.obtenerFila(nombre), 2);*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJornadas = new javax.swing.JTable();
        cbJornadas = new javax.swing.JComboBox<>();
        rbtnIda = new javax.swing.JRadioButton();
        rbtnVuelta = new javax.swing.JRadioButton();
        cbJornadas2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("GESTIONAR ENCUENTROS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 60));

        tblJornadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblJornadas);

        cbJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJornadasActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnIda);
        rbtnIda.setSelected(true);
        rbtnIda.setText("Ida");
        rbtnIda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnIdaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnVuelta);
        rbtnVuelta.setText("Vuelta");
        rbtnVuelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVueltaActionPerformed(evt);
            }
        });

        cbJornadas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJornadas2ActionPerformed(evt);
            }
        });

        jLabel3.setText("1ro seleccione una jornada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(rbtnIda)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnVuelta)
                        .addGap(59, 59, 59)
                        .addComponent(cbJornadas2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnIda)
                    .addComponent(rbtnVuelta)
                    .addComponent(cbJornadas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 98, 710, -1));

        btnRegresar.setText("regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        btnAsignar.setText("Gestionar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 95, -1));

        btnResultados.setText("resultados");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListaJornadas.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cbJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJornadasActionPerformed
        // TODO add your handling code here:
        this.tblJornadas.setEnabled(true);
        this.cargarTablaIda(this.cbJornadas.getSelectedIndex()+1);
        
    }//GEN-LAST:event_cbJornadasActionPerformed

    private void rbtnIdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnIdaActionPerformed
        // TODO add your handling code here:
        this.tblJornadas.setEnabled(false);
        this.cbJornadas.setEnabled(true);
        this.cbJornadas2.setEnabled(false);
       
    }//GEN-LAST:event_rbtnIdaActionPerformed

    private void rbtnVueltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVueltaActionPerformed
        // TODO add your handling code here:
        this.tblJornadas.setEnabled(false);
        this.cbJornadas.setEnabled(false);
        this.cbJornadas2.setEnabled(true);
      
        
    }//GEN-LAST:event_rbtnVueltaActionPerformed

    private void cbJornadas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJornadas2ActionPerformed
        // TODO add your handling code here:
        this.tblJornadas.setEnabled(true);
        this.cargarTablaVuelta(this.cbJornadas2.getSelectedIndex()+1);
        
    }//GEN-LAST:event_cbJornadas2ActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
        int fila=0;
        int columna1=0;
        int columna2=3;
        String nombre1="";
        String nombre2="";
        Equipo equipo1;
        Equipo equipo2;
        
      
        int jornada=0;

        try{

            fila=this.tblJornadas.getSelectedRow();
            nombre1= (String)this.tblJornadas.getValueAt(fila,columna1);
            nombre2= (String)this.tblJornadas.getValueAt(fila,columna2);

          equipo1=Configuracion.equipos.buscarEquipoPorNombre(nombre1);
          equipo2=Configuracion.equipos.buscarEquipoPorNombre(nombre2);
          
          if(this.rbtnIda.isSelected()){
              jornada = this.cbJornadas.getSelectedIndex()+1;
            
          }else if(this.rbtnVuelta.isSelected()){
              jornada = this.cbJornadas2.getSelectedIndex()+Configuracion.equipos.cantidadDeEquipos();
                        }
          
                   
          
            Plantel p = equipo1.obtenerPlantel(jornada);
            Plantel p2 = equipo2.obtenerPlantel(jornada);
            
       if(p!=null && p2!=null){
           
            FrameGestionResultado frm = new FrameGestionResultado(equipo1, equipo2, jornada);
            frm.setLocationRelativeTo(null);
            frm.setVisible(true);
            
           
       }else{
           JOptionPane.showMessageDialog(this, "Falta Convocar");
           
       }  
                   
            

        }catch(IndexOutOfBoundsException e){
         JOptionPane.showMessageDialog(this, "ELIGE ELEMENTO: "+e);
          }       
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        // TODO add your handling code here:
        int jornada=0;
        if(this.rbtnIda.isSelected()){
            jornada = this.cbJornadas.getSelectedIndex();
        }else if(this.rbtnVuelta.isSelected()){
            jornada = this.cbJornadas2.getSelectedIndex()+Configuracion.equipos.cantidadDeEquipos()-1;
        }
        
        FrameListaEncuentros frm = new FrameListaEncuentros(jornada);
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
       
    }//GEN-LAST:event_btnResultadosActionPerformed
 
    
   
    
 
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGestionJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGestionJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGestionJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGestionJornadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGestionJornadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnResultados;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbJornadas;
    private javax.swing.JComboBox<String> cbJornadas2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnIda;
    private javax.swing.JRadioButton rbtnVuelta;
    private javax.swing.JTable tblJornadas;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaIda(int jor){
        
      
       
       
       DefaultTableModel table = new DefaultTableModel(this.calendario.getMatrizEncuentrosIda(jor),
                this.calendario.cabeceraEncuentrosIda());
       
      /* DefaultTableModel table = new DefaultTableModel((String[][])this.arr.get(jor-1),
                this.calendario.cabeceraEncuentrosIda());
       */
        this.tblJornadas.setModel(table);
    
      
      this.tblJornadas.setRowHeight(50);
      
       this.tblJornadas.getColumnModel().getColumn(0).setPreferredWidth(200);
       this.tblJornadas.getColumnModel().getColumn(1).setPreferredWidth(5);
       this.tblJornadas.getColumnModel().getColumn(2).setPreferredWidth(5);
       this.tblJornadas.getColumnModel().getColumn(3).setPreferredWidth(200);
    }
    
      private void cargarTablaVuelta(int jor){
        
          try {
              
               
       DefaultTableModel table = new DefaultTableModel(this.calendario.getMatrizEncuentrosVuelta(jor),
                this.calendario.cabeceraEncuentrosVuelta());
       
        this.tblJornadas.setModel(table);
      //  this.tablaPersonas.getColumnModel().getColumn(0).setPreferredWidth(10)
        this.tblJornadas.setRowHeight(50);
      
       this.tblJornadas.getColumnModel().getColumn(0).setPreferredWidth(200);
       this.tblJornadas.getColumnModel().getColumn(1).setPreferredWidth(5);
       this.tblJornadas.getColumnModel().getColumn(2).setPreferredWidth(5);
       this.tblJornadas.getColumnModel().getColumn(3).setPreferredWidth(200);
              
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "ERROR: "+e);
          }
       
       /*DefaultTableModel table = new DefaultTableModel((String[][])this.arr.get(jor-1+Configuracion.equipos.cantidadDeEquipos()),
                this.calendario.cabeceraEncuentrosVuelta());*/
      ;
    }
    
    private void cargarcomboBox(){
        
         for(int i=0;i<Configuracion.equipos.cantidadDeEquipos()-1;i++){
            
            this.cbJornadas.addItem("Jornada "+(i+1));
            
        }
         
        for(int j=Configuracion.equipos.cantidadDeEquipos()-1;j<2*(Configuracion.equipos.cantidadDeEquipos()-1);j++){
            
            this.cbJornadas2.addItem("Jornada "+(j+1));
        } 
    }
    
    private int obtenerFila(String equipo){
        int result=0;
        int i=0;
        while(i<this.tblJornadas.getRowCount()){
            if(equipo.equals((String)this.tblJornadas.getValueAt(i,0))){
                
               result=i;
               break;
            }
            i++;
        }
        
        
        return result;
    }
    
    
    private void crearJornadas(){
        
        
        
        int cant = Configuracion.equipos.cantidadDeEquipos();
        for(int i=0;i<(cant-1)*2;i++){
            Configuracion.fechas.agregarFecha(new Fecha(i+1));
                   
        }
      //  this.estadosJornadas= true;
    }
    
  /**  private void guardarJornadas(){
        
         for(int i=0;i<Configuracion.equipos.cantidadDeEquipos()-1;i++){
            
            
            this.arr.add(this.calendario.getMatrizEncuentrosIda(i+1));
        }
         
        for(int j=Configuracion.equipos.cantidadDeEquipos()-1;j<2*(Configuracion.equipos.cantidadDeEquipos()-1);j++){
            
            
            this.arr.add(this.calendario.getMatrizEncuentrosVuelta(j+1));
        }  
        
    }*/
    
    
}
