/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Estadio;
import Listas.ArregloEstadio;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import Listas.*;
import Entidades.*;
import Sistema.Configuracion;
import java.awt.Color;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;


/**
 *
 * @author ACER
 */
public class FrameEquipo extends javax.swing.JFrame {

    /**
     * Creates new form frmEquipo
     */
    
    Equipo e;
    public FrameEquipo() {
        initComponents();
      //  this.getContentPane().setBackground(Color.BLUE);
        
        
        
        //ArrayList<Estadio> estadios = Sistema.Configuracion.estadios.getEstadios();
       /* DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        int i=0;
        for(Estadio e : Sistema.Configuracion.estadios.getEstadios()){
            
            modelo.addElement(e);
        }
        
        this.cboEstadio.setModel(modelo);
        this.btnModificar.setEnabled(false);*/
        this.btnModificar.setEnabled(false);
        
    }
    
    public FrameEquipo(Equipo e){
        initComponents();
        this.e=e;
        this.inicializarCampos(e);
        this.btnAgregar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtEntrenador = new javax.swing.JTextField();
        txtEstadio = new javax.swing.JTextField();
        cboEstadios = new javax.swing.JComboBox<>();
        lblNombre1 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        cboEntrenadores = new javax.swing.JComboBox<>();
        lblNombre5 = new javax.swing.JLabel();
        lblNombre6 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jcalendar = new com.toedter.calendar.JDateChooser();
        spJugadores = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 204, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre.setText("NOMBRE");

        txtEntrenador.setEditable(false);

        txtEstadio.setEditable(false);
        txtEstadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadioActionPerformed(evt);
            }
        });

        cboEstadios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadiosActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre1.setText("ENTRENADOR");

        lblNombre2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre2.setText("JUGADORES");

        lblNombre3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre3.setText("ESTADIO");

        cboEntrenadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEntrenadoresActionPerformed(evt);
            }
        });

        lblNombre5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre5.setText("CIUDAD");

        lblNombre6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre6.setText("FUNDACION");

        spJugadores.setModel(new javax.swing.SpinnerNumberModel(11, 11, 30, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(lblNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtEntrenador, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstadio))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboEstadios, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboEntrenadores, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(spJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jcalendar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre1)
                    .addComponent(cboEntrenadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEstadios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre2)
                    .addComponent(spJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre5)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre6)
                    .addComponent(jcalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        btnAgregar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
     
     Estadio estadio; 
     Equipo equipo;
     
     try{
         
       if(!this.validarFormAgregar()){
           
       }else{
          /* estadio= new Estadio(this.txtEstadio.getText(), Integer.parseInt(this.txtCapacidad.getText()));
            Configuracion.estadios.agregarEstadio(estadio);*/
     
            estadio = Configuracion.estadios.buscarEstadioPorNombre(this.txtEstadio.getText());
            
            equipo = new Equipo(this.txtNombre.getText(), 
            (int)this.spJugadores.getValue(),(Entrenador)this.cboEntrenadores.getSelectedItem(), estadio,
            this.txtCiudad.getText(),this.jcalendar.getDate());
     
            Configuracion.equipos.agregarEquipo(equipo);  
            JOptionPane.showMessageDialog(this, "AGREGADO EXITOSAMENTE");
            this.limpiar();
            
       }
         
        
     }catch(NumberFormatException e){
         JOptionPane.showMessageDialog(this, "ERROR:"+e);
     }
    
    
    
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try{
            int p =0;
            if(!this.validarFormModificar()){
               
            }else{
                p = Configuracion.equipos.getPosicion(e);
               e.setEntrenador((Entrenador)this.cboEntrenadores.getSelectedItem());
               e.setNombre(this.txtNombre.getText());
               e.setNumJugadores((int)this.spJugadores.getValue());
               e.getEstadio().setNombre(this.txtEstadio.getText());
              
               
               Configuracion.equipos.getEquipos().set(p,e);
               JOptionPane.showMessageDialog(this, "MODIFICADO EXITOSO");
               
               FrameGestionEquipos frm = new FrameGestionEquipos();
               frm.setLocationRelativeTo(null);
               frm.setVisible(true);
               this.dispose();
            }
            
            
            
            
            
        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this,"ERROR");
        }
        
      
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
     
        this.dispose();
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadioActionPerformed

    private void cboEstadiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadiosActionPerformed
        // TODO add your handling code here:
        String estad = (String)this.cboEstadios.getSelectedItem().toString();
        this.txtEstadio.setText(estad);
        
       
    }//GEN-LAST:event_cboEstadiosActionPerformed

    private void cboEntrenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEntrenadoresActionPerformed
        // TODO add your handling code here:
        String entrenador = (String)this.cboEntrenadores.getSelectedItem().toString();
        this.txtEntrenador.setText(entrenador);
    }//GEN-LAST:event_cboEntrenadoresActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.cargarComboBox();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboEntrenadores;
    private javax.swing.JComboBox<String> cboEstadios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private com.toedter.calendar.JDateChooser jcalendar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombre5;
    private javax.swing.JLabel lblNombre6;
    private javax.swing.JSpinner spJugadores;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtEntrenador;
    private javax.swing.JTextField txtEstadio;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

   private boolean validarFormAgregar(){
        boolean result = false;
        if(this.txtNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NOMBRE DEL EQUIPO", "NOMBRE", ERROR_MESSAGE);
        
        }else if(Configuracion.equipos.buscarEquipoPorNombre(this.txtNombre.getText()) != null){
            JOptionPane.showMessageDialog(this, "EL EQUIPO YA EXISTE", "NOMBRE",ERROR_MESSAGE);
            
        }else if(this.txtEntrenador.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NOMBRE DEL ENTRENADOR", "ENTRENADOR", ERROR_MESSAGE);
        }else if(Configuracion.estadios.buscarEstadioPorNombre(this.txtEstadio.getText()) == null){
            JOptionPane.showMessageDialog(this, "EL ESTADIO YA EXISTE", "ESTADIO",ERROR_MESSAGE);
        }else if(this.txtEstadio.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA ESTADIO", "ESTADIO", ERROR_MESSAGE);
        }else{
           result = true;  
        }
        
        return result;     
    } 
   
   private boolean validarFormModificar(){
        boolean result = false;
        if(this.txtNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NOMBRE DEL EQUIPO", "NOMBRE", ERROR_MESSAGE);
        
        }else if(!this.txtNombre.getText().equalsIgnoreCase(e.getNombre())  && Configuracion.equipos.buscarEquipoPorNombre(this.txtNombre.getText()) != null){
            JOptionPane.showMessageDialog(this, "EL EQUIPO YA EXISTE", "NOMBRE",ERROR_MESSAGE); 
        }else if(this.txtEntrenador.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NOMBRE DEL ENTRENADOR", "ENTRENADOR", ERROR_MESSAGE);
        }else if(!this.txtEstadio.getText().equalsIgnoreCase(e.getEstadio().getNombre())&& Configuracion.estadios.buscarEstadioPorNombre(this.txtEstadio.getText()) != null){
        
            
            
               JOptionPane.showMessageDialog(this, "EL ESTADIO YA EXISTE", "ESTADIO",ERROR_MESSAGE); 
            
            
            
        }else if(this.txtEstadio.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA ESTADIO", "ESTADIO", ERROR_MESSAGE);
        }
       
        else{
            result = true;
        }
        return result;     
    } 
    
    public void limpiar(){
        
        this.txtEntrenador.setText("");
        this.txtEstadio.setText("");
        this.txtNombre.setText("");
       
    }
    
    public void inicializarCampos(Equipo e){
        
        this.txtEstadio.setText(e.getEstadio().getNombre());
        this.txtEntrenador.setText(e.getEntrenador().getNombre());
        this.txtNombre.setText(e.getNombre());
        
       
    }
    
    private void cargarComboBox(){
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        
        for(Estadio e : Configuracion.estadios.getEstadios()){
            
            combo.addElement(e);
        }
      
      
      
      
      
    /*  for(int i=0;i<Configuracion.estadios.cantidadDeEstadios();i++){
          
          combo.addElement(Configuracion.estadios.getEstadios().get(i));
      }*/
      
        this.cboEstadios.setModel(combo);
        
        
        DefaultComboBoxModel combo2 = new DefaultComboBoxModel();
        
        for(Entrenador e : Configuracion.personas.getListaEntrenador()){
            combo2.addElement(e);
        }
        this.cboEntrenadores.setModel(combo2);
    }
    
    
}


