/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import Entidades.Torneo;
import Sistema.Configuracion;
import java.util.ArrayList;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author ACER
 */
public class FrameTabla extends javax.swing.JFrame {

    /**
     * Creates new form FrameTabla
     */
    public FrameTabla() {
        initComponents();
        cargarTabla();
        
        
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCentro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTablaPosicion = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TABLA LISTA DE POSICIONES\n");

        panCentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Si los resultados no son correctos haga click aqui");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panCentro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 310, 20));

        tablaTablaPosicion.setBackground(new java.awt.Color(255, 0, 0));
        tablaTablaPosicion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaTablaPosicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaTablaPosicion);

        panCentro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 750, 430));

        btnSalir.setText("regresar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panCentro.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 80, -1));

        lblFondo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tablaPosicion.jpg"))); // NOI18N
        lblFondo.setText("lblFondo ");
        panCentro.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 510));

        getContentPane().add(panCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        FrameTabla frm = new FrameTabla();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPanel panCentro;
    private javax.swing.JTable tablaTablaPosicion;
    // End of variables declaration//GEN-END:variables

    
      private void cargarTabla(){
        
            DefaultTableModel table = new DefaultTableModel(Configuracion.torneo.getTabla().mostrarTablita(),
                    Configuracion.torneo.getTabla().getTituloTabla());
            this.tablaTablaPosicion.setModel(table);
        this.tablaTablaPosicion.setRowHeight(30);
        

         //Ordenando
         
     /*  table =  (DefaultTableModel) this.tablaTablaPosicion.getModel();
        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(table);
        this.tablaTablaPosicion.setRowSorter(sorter);*/
        
        this.tablaTablaPosicion.getColumnModel().getColumn(0).setPreferredWidth(30); 
        this.tablaTablaPosicion.getColumnModel().getColumn(1).setPreferredWidth(150); 
        this.tablaTablaPosicion.getColumnModel().getColumn(2).setPreferredWidth(30); 
        this.tablaTablaPosicion.getColumnModel().getColumn(3).setPreferredWidth(30); 
        this.tablaTablaPosicion.getColumnModel().getColumn(4).setPreferredWidth(30); 
        this.tablaTablaPosicion.getColumnModel().getColumn(5).setPreferredWidth(30); 
        this.tablaTablaPosicion.getColumnModel().getColumn(6).setPreferredWidth(30); 
        this.tablaTablaPosicion.getColumnModel().getColumn(7).setPreferredWidth(30); 
        this.tablaTablaPosicion.getColumnModel().getColumn(8).setPreferredWidth(30); 
        this.tablaTablaPosicion.getColumnModel().getColumn(9).setPreferredWidth(30); 
       

        





          //   this.tablaTablaPosicion.getRowSorter().toggleSortOrder(9);
         
    }       

  /* private void mostrarEscudos(){
       
       
   }
   
   private String obtenerURL(String nombre){
       
       ArrayList<String> url = new ArrayList<>();
       url.add("Imagenes/entrar.png");
       
       return url.get(0);
       
   }*/

}
