/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Sistema.Configuracion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FramePichichi extends javax.swing.JFrame {

    /**
     * Creates new form FramePichichi
     */
    public FramePichichi() {
        initComponents();
        this.cargaTabla();
        this.mostrarPichichi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPichichi = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblPichichi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GOLEADORES LIGA 1");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Hacer Click para ver detalles");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 180, -1));

        tablaPichichi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPichichi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPichichiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPichichi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 360));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        jLabel1.setText("Pichichi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 49, -1));
        getContentPane().add(lblPichichi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 121, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pichich.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tablaPichichiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPichichiMouseClicked
        // TODO add your handling code here:
        int fila = this.tablaPichichi.getSelectedRow();
        String nombre = (String)this.tablaPichichi.getValueAt(fila, 1);
        
        JOptionPane.showMessageDialog(this,Configuracion.personas.buscarJugadorPorNombre(nombre).mostrarGolesMarcados());
        
        
    }//GEN-LAST:event_tablaPichichiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePichichi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePichichi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePichichi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePichichi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePichichi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPichichi;
    private javax.swing.JTable tablaPichichi;
    // End of variables declaration//GEN-END:variables

    private void cargaTabla(){
        DefaultTableModel table = new DefaultTableModel(Configuracion.personas.ordenarGoleadores(),
        Configuracion.personas.cabeceraGoleadores());
        
        this.tablaPichichi.setModel(table);
        this.tablaPichichi.getColumnModel().getColumn(0).setPreferredWidth(50); 
        this.tablaPichichi.getColumnModel().getColumn(1).setPreferredWidth(150); 
        this.tablaPichichi.getColumnModel().getColumn(2).setPreferredWidth(150); 
        this.tablaPichichi.getColumnModel().getColumn(3).setPreferredWidth(50); 
    }

    private void mostrarPichichi(){
        String nombre="";
        
        try {
            if(this.tablaPichichi.getValueAt(0, 1)!=null){
          nombre = (String)this.tablaPichichi.getValueAt(0, 1);  
        }
        
        
        this.lblPichichi.setText(nombre);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error: "+e);
        }
        
        
    }
    
    
    
}
        

