/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Arbitro;
import Entidades.Convocado;
import Entidades.Encuentro;
import Entidades.Equipo;
import Entidades.Fecha;
import Entidades.Gol;
import Entidades.Jugador;
import Entidades.Plantel;
import Entidades.Tarjeta;
import Entidades.TipoDeGol;
import Entidades.Ubigeo;
import Enumerados.Demarcacion;
import Enumerados.*;
import Sistema.Configuracion;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author ACER
 */
public class FrameGestionResultado extends javax.swing.JFrame {

    /**
     * Creates new form FrameGestionResultado
     */
    
    Equipo equipo1;
    Equipo equipo2;
    int jornada;
   // int jornada2;
    Encuentro encuentro1;
   // Encuentro encuentro2;
    Fecha fecha;
    String g1,g2;
    Date fechaEncuentro;
    
   
    String codigo; 
    
    ArrayList<String> minutos;
           
    public FrameGestionResultado() {
        initComponents();
        
    }

    
      public FrameGestionResultado(Equipo equipo1,Equipo equipo2,int jornada1) {
        initComponents();
        minutos = new ArrayList<>();
        
        this.equipo1 = equipo1;
        this.equipo2 = equipo2;
        this.jornada=jornada1;
       // this.jornada2=jornada2;
        
        this.cargarComboBox();
        
        this.cargarNombreEquipos();
        
        
        
        
        this.mostrarTxtAreas(1);
        this.mostrarTxtAreas(2);
      
       
        mostrarTiTuloJornada();
        
        this.lblEstadio.setText(equipo1.getEstadio().getNombre());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbConvocados2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbConvocados1 = new javax.swing.JComboBox<>();
        lblEquipo2 = new javax.swing.JLabel();
        lblEquipo1 = new javax.swing.JLabel();
        btnGolLocal = new javax.swing.JButton();
        btnGolVisit = new javax.swing.JButton();
        btnTarjeta1 = new javax.swing.JButton();
        cbTarjetas1 = new javax.swing.JComboBox<>();
        btnTarjeta2 = new javax.swing.JButton();
        cbTarjetas2 = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        spLocal = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spVisitante = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaVisitante = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaLocal = new javax.swing.JTextArea();
        btnGenerar = new javax.swing.JButton();
        jdcCalendario = new com.toedter.calendar.JDateChooser();
        cbTipogGolLocal = new javax.swing.JComboBox<>();
        cbTipoGolVisitante = new javax.swing.JComboBox<>();
        spGolesLocal = new javax.swing.JSpinner();
        spGolesVisitante = new javax.swing.JSpinner();
        spMinutos2 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spMinutos1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblCodigoGenerado = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblJornadaDeJornada = new javax.swing.JLabel();
        lblEstadio = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbArbitro = new javax.swing.JComboBox<>();
        spMinutosTarjeta1 = new javax.swing.JSpinner();
        spMinutosTarjeta2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setForeground(new java.awt.Color(0, 0, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbConvocados2.setBackground(new java.awt.Color(255, 0, 0));
        cbConvocados2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(cbConvocados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 160, 140, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOCAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VISITANTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        cbConvocados1.setBackground(new java.awt.Color(255, 0, 0));
        cbConvocados1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        cbConvocados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConvocados1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbConvocados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, -1));

        lblEquipo2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblEquipo2.setForeground(new java.awt.Color(255, 0, 0));
        lblEquipo2.setText("EQUIPO2");
        lblEquipo2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        getContentPane().add(lblEquipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 220, 44));

        lblEquipo1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblEquipo1.setForeground(new java.awt.Color(255, 0, 0));
        lblEquipo1.setText("EQUIPO1");
        lblEquipo1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        getContentPane().add(lblEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 237, 44));

        btnGolLocal.setText("+ LOCAL");
        btnGolLocal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        btnGolLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGolLocalActionPerformed(evt);
            }
        });
        getContentPane().add(btnGolLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 407, 87, 30));

        btnGolVisit.setText("VISITANTE+");
        btnGolVisit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        btnGolVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGolVisitActionPerformed(evt);
            }
        });
        getContentPane().add(btnGolVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 407, 80, 30));

        btnTarjeta1.setText("+");
        btnTarjeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjeta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        cbTarjetas1.setBackground(new java.awt.Color(255, 0, 0));
        cbTarjetas1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(cbTarjetas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 100, -1));

        btnTarjeta2.setText("+");
        btnTarjeta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjeta2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));

        cbTarjetas2.setBackground(new java.awt.Color(255, 0, 0));
        cbTarjetas2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(cbTarjetas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 160, 100, -1));

        btnRegistrar.setBackground(new java.awt.Color(255, 0, 0));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TARJETA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 67, -1));

        spLocal.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1, 1));
        getContentPane().add(spLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 50, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GOL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JUGADOR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 67, -1));

        spVisitante.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1, 1));
        getContentPane().add(spVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 50, 20));

        txtaVisitante.setEditable(false);
        txtaVisitante.setBackground(new java.awt.Color(255, 0, 0));
        txtaVisitante.setColumns(20);
        txtaVisitante.setRows(5);
        jScrollPane1.setViewportView(txtaVisitante);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 137, 225));

        txtaLocal.setEditable(false);
        txtaLocal.setBackground(new java.awt.Color(255, 0, 0));
        txtaLocal.setColumns(20);
        txtaLocal.setRows(5);
        jScrollPane2.setViewportView(txtaLocal);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 143, 225));

        btnGenerar.setText("GENERAR");
        btnGenerar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 80, 30));
        getContentPane().add(jdcCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 129, -1));

        cbTipogGolLocal.setBackground(new java.awt.Color(255, 0, 0));
        cbTipogGolLocal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(cbTipogGolLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 114, -1));

        cbTipoGolVisitante.setBackground(new java.awt.Color(255, 0, 0));
        cbTipoGolVisitante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(cbTipoGolVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 114, -1));

        spGolesLocal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        spGolesLocal.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spGolesLocal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(spGolesLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 60, 23));

        spGolesVisitante.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        spGolesVisitante.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spGolesVisitante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(spGolesVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 70, 60, 23));

        spMinutos2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        getContentPane().add(spMinutos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MINUTO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 517, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GOL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MINUTO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 509, -1, -1));

        spMinutos1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        getContentPane().add(spMinutos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DEFINICION");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 563, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DEFINICION");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 555, -1, -1));

        lblCodigoGenerado.setBackground(new java.awt.Color(102, 255, 255));
        lblCodigoGenerado.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblCodigoGenerado.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblCodigoGenerado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 210, 19));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CODIGO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        lblJornadaDeJornada.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblJornadaDeJornada.setForeground(new java.awt.Color(255, 0, 0));
        lblJornadaDeJornada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(lblJornadaDeJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 185, 21));

        lblEstadio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEstadio.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblEstadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 210, 23));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ESTADIO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ARBITRO");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        cbArbitro.setBackground(new java.awt.Color(255, 0, 0));
        cbArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbArbitroActionPerformed(evt);
            }
        });
        getContentPane().add(cbArbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 190, -1));

        spMinutosTarjeta1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        getContentPane().add(spMinutosTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        spMinutosTarjeta2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        getContentPane().add(spMinutosTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MIN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 29, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("MIN");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 29, -1));

        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 90, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("JUGADOR");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 67, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TARJETA");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 67, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/peruvian primera division.jpg"))); // NOI18N
        lblFondo.setText("jLabel16");
        lblFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
       
        /*g1=this.txtGoles1.getText();
        g2=this.txtGoles2.getText();*/
        
       /* g1 = this.spGolesLocal.getValue().toString();
        g2 = this.spGolesVisitante.getValue().toString();*/
       
       int confirmado = JOptionPane.showConfirmDialog(this,"¿registrar...?");
                
                if(JOptionPane.OK_OPTION==confirmado){
                    
                    this.dispose();
                    
                    JOptionPane.showMessageDialog(this, "Registro Existoso");
                     
                    
                }
        
        
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        
        int confirmado = JOptionPane.showConfirmDialog(this,"¿registrar...?");
                
                if(JOptionPane.OK_OPTION==confirmado){
                    
                    if(this.jdcCalendario.getDate()!=null && (Arbitro)this.cbArbitro.getSelectedItem()!=null){
         
            this.crearEncuentro(equipo1, equipo2);
        this.asignarResultado(Integer.parseInt(this.spGolesLocal.getValue().toString()),
                Integer.parseInt(this.spGolesVisitante.getValue().toString()));
        
        this.jdcCalendario.setEnabled(false);
        this.spGolesLocal.setEnabled(false);
        this.spGolesVisitante.setEnabled(false);
        
        this.btnCancelar.setEnabled(false);
        this.btnGenerar.setEnabled(false);
        this.btnRegistrar.setEnabled(true);
        
        this.spLocal.setEnabled(true);
        this.spVisitante.setEnabled(true);
        this.cbConvocados1.setEnabled(true);
        this.cbConvocados2.setEnabled(true);
        this.btnGolLocal.setEnabled(true);
        this.btnGolVisit.setEnabled(true);
        this.spMinutos1.setEnabled(true);
        this.spMinutos2.setEnabled(true);
        this.cbTipogGolLocal.setEnabled(true);
        this.cbTipoGolVisitante.setEnabled(true);
        this.btnTarjeta1.setEnabled(true);
        this.btnTarjeta2.setEnabled(true);
        
        this.cbTarjetas1.setEnabled(true);
        this.cbTarjetas2.setEnabled(true);
        this.spMinutosTarjeta1.setEnabled(true);
        this.spMinutosTarjeta2.setEnabled(true);
        
        this.btnGenerar.setEnabled(false);
            
        }else{
            
            if(this.jdcCalendario.getDate()==null){
               JOptionPane.showMessageDialog(this, "Asigne una Fecha de Encuentro"); 
            }else{
                JOptionPane.showMessageDialog(this, "Asigne un arbitro para el encuentro");
            }
            
        }
                     
                    
     }
        
      
        
        
       
        
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnGolLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGolLocalActionPerformed
        
      if(asignarMinuto(String.valueOf(this.spMinutos1.getValue()))){
         
        //for(int i=0;i<(int)this.spLocal.getValue();i++){
        
            this.asignarGolLocal(equipo1);  
        
           
         // }   
           
        }else{
            JOptionPane.showMessageDialog(this, "Ya ocurrio gol");
        }
        
    }//GEN-LAST:event_btnGolLocalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        if(equipo1.obtenerPlantel(jornada).isbEncuentro()==true){
        
        
        this.btnGenerar.setEnabled(false);
        this.btnRegistrar.setEnabled(false);
        
        this.spGolesLocal.setEnabled(false);
        this.spGolesVisitante.setEnabled(false);
        this.cbConvocados1.setEnabled(false);
        this.cbConvocados2.setEnabled(false);
        this.btnGolLocal.setEnabled(false);
        this.btnGolVisit.setEnabled(false);
        this.spLocal.setEnabled(false);
        this.spVisitante.setEnabled(false);
        this.spMinutos1.setEnabled(false);
        this.spMinutos2.setEnabled(false);
        this.cbTipogGolLocal.setEnabled(false);
        this.cbTipoGolVisitante.setEnabled(false);
        this.btnTarjeta1.setEnabled(false);
        this.btnTarjeta2.setEnabled(false);
        
        this.cbTarjetas1.setEnabled(false);
        this.cbTarjetas2.setEnabled(false);
        this.spMinutosTarjeta1.setEnabled(false);
        this.spMinutosTarjeta2.setEnabled(false);
           
        JOptionPane.showMessageDialog(this, "ENCUENTRO ASIGNADO");
        
        }else{
        this.btnGenerar.setEnabled(true);
        
        this.btnRegistrar.setEnabled(false);
        this.btnCancelar.setEnabled(true);
        
        this.cbConvocados1.setEnabled(false);
        this.cbConvocados2.setEnabled(false);
        this.btnGolLocal.setEnabled(false);
        this.btnGolVisit.setEnabled(false);
        this.spLocal.setEnabled(false);
        this.spVisitante.setEnabled(false);
        this.spMinutos1.setEnabled(false);
        this.spMinutos2.setEnabled(false);
        this.cbTipogGolLocal.setEnabled(false);
        this.cbTipoGolVisitante.setEnabled(false);  
        this.btnTarjeta1.setEnabled(false);
        this.btnTarjeta2.setEnabled(false);
        
        this.cbTarjetas1.setEnabled(false);
        this.cbTarjetas2.setEnabled(false);
        this.spMinutosTarjeta1.setEnabled(false);
        this.spMinutosTarjeta2.setEnabled(false);
        
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnGolVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGolVisitActionPerformed
        // TODO add your handling code here:
       
        if(asignarMinuto(String.valueOf(this.spMinutos2.getValue()))){
            
        //   for(int i=0;i<(int)this.spMinutos2.getValue();i++){
           this.asignarGolVisitante(equipo2);  
          //  }   
        }else{
            JOptionPane.showMessageDialog(this, "Ya ocurrio gol");
        }
    }//GEN-LAST:event_btnGolVisitActionPerformed

    private void cbConvocados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConvocados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbConvocados1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        FrameGestionJornadas frm = new FrameGestionJornadas(jornada);
                    
                   
                    frm.setLocationRelativeTo(null);
                    frm.setVisible(true);
                    this.dispose();
                    
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnTarjeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjeta1ActionPerformed
        // TODO add your handling code here:
         Convocado c = this.equipo1.obtenerPlantel(jornada).obtenerConvocadoPorNombre((String)this.cbConvocados1.getSelectedItem());
         
         if(c.asignarTarjeta(new Tarjeta((TipoTarjeta)this.cbTarjetas1.getSelectedItem(), (int)this.spMinutosTarjeta1.getValue()))){
             JOptionPane.showMessageDialog(this, "ASIGNADO");
         }else{
              JOptionPane.showMessageDialog(this, "LIMITE DE TARJETAS");
         }
          
    }//GEN-LAST:event_btnTarjeta1ActionPerformed

    private void btnTarjeta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjeta2ActionPerformed
        // TODO add your handling code here:
        Convocado c = this.equipo2.obtenerPlantel(jornada).obtenerConvocadoPorNombre((String)this.cbConvocados2.getSelectedItem());
         
        
         if(c.asignarTarjeta(new Tarjeta((TipoTarjeta)this.cbTarjetas2.getSelectedItem(), (int)this.spMinutosTarjeta2.getValue()))){
             JOptionPane.showMessageDialog(this, "ASIGNADO");
         }else{
              JOptionPane.showMessageDialog(this, "LIMITE DE TARJETAS");
         }
        
         
    }//GEN-LAST:event_btnTarjeta2ActionPerformed

    private void cbArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbArbitroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGestionResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGestionResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGestionResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGestionResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGestionResultado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGolLocal;
    private javax.swing.JButton btnGolVisit;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnTarjeta1;
    private javax.swing.JButton btnTarjeta2;
    private javax.swing.JComboBox<String> cbArbitro;
    private javax.swing.JComboBox<String> cbConvocados1;
    private javax.swing.JComboBox<String> cbConvocados2;
    private javax.swing.JComboBox<String> cbTarjetas1;
    private javax.swing.JComboBox<String> cbTarjetas2;
    private javax.swing.JComboBox<String> cbTipoGolVisitante;
    private javax.swing.JComboBox<String> cbTipogGolLocal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcCalendario;
    private javax.swing.JLabel lblCodigoGenerado;
    private javax.swing.JLabel lblEquipo1;
    private javax.swing.JLabel lblEquipo2;
    private javax.swing.JLabel lblEstadio;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblJornadaDeJornada;
    private javax.swing.JSpinner spGolesLocal;
    private javax.swing.JSpinner spGolesVisitante;
    private javax.swing.JSpinner spLocal;
    private javax.swing.JSpinner spMinutos1;
    private javax.swing.JSpinner spMinutos2;
    private javax.swing.JSpinner spMinutosTarjeta1;
    private javax.swing.JSpinner spMinutosTarjeta2;
    private javax.swing.JSpinner spVisitante;
    private javax.swing.JTextArea txtaLocal;
    private javax.swing.JTextArea txtaVisitante;
    // End of variables declaration//GEN-END:variables

    private void cargarComboBox(){
            
            Plantel p = this.equipo1.obtenerPlantel(jornada);
            Plantel p2 = this.equipo2.obtenerPlantel(jornada);
       if(p!=null && p2!=null){
           
          for(Convocado c : p.getConvocados()){
            
            this.cbConvocados1.addItem(c.getJugador().getNombre());
        }
        
         for(Convocado c : p2.getConvocados()){
            
            this.cbConvocados2.addItem(c.getJugador().getNombre());
        }          
           
       }else{
           JOptionPane.showMessageDialog(this, "Falta Convocar");
           
       }         
        
       
       //DEFINICION
       
       DefaultComboBoxModel comboD = new DefaultComboBoxModel(TipoGoles.values()); 
         this.cbTipogGolLocal.setModel(comboD);
        DefaultComboBoxModel comboE = new DefaultComboBoxModel(TipoGoles.values()); 
         this.cbTipoGolVisitante.setModel(comboE);
         
         //ARBITROS
         
        ArrayList<Arbitro> arbitros = Configuracion.personas.getListaArbitro();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(Arbitro  a: arbitros){
            model.addElement(a);
        }
        this.cbArbitro.setModel(model);
        
        
        //TARJETAS
        
        DefaultComboBoxModel combo1 = new DefaultComboBoxModel(TipoTarjeta.values());
        this.cbTarjetas1.setModel(combo1);
        
        DefaultComboBoxModel combo2 = new DefaultComboBoxModel(TipoTarjeta.values());
        this.cbTarjetas2.setModel(combo2);
       
    }
    
    private void cargarNombreEquipos(){
        this.lblEquipo1.setText(this.equipo1.getNombre());
        this.lblEquipo2.setText(this.equipo2.getNombre());
        
    }
    
   /* private boolean crearFecha(int jornada){
        boolean result=false;
       if( Configuracion.fechas.agregarFecha(new Fecha(jornada))){
           JOptionPane.showMessageDialog(this, "Fecha Agregada");
           result=true;
       }else{
           JOptionPane.showMessageDialog(this, "Fecha ya creada");
          
       }
         
        return result;
       
    }*/
    
    private void crearEncuentro(Equipo e1,Equipo e2){
        
        //Creando encuentro
        
        encuentro1 = new Encuentro(e1.obtenerPlantel(jornada), e2.obtenerPlantel(jornada), e1.getEstadio()
                , this.jdcCalendario.getDate(), jornada,(Arbitro)this.cbArbitro.getSelectedItem());
        
        //Generar el codigo en el frame, una vez creado el encuentro,
        
        this.lblCodigoGenerado.setText(encuentro1.getId());
        
      
        
      
        
        
        //Agregando encuentro
      if( Configuracion.fechas.obtenerFechaPorJornada(jornada).agregarEncuentros(encuentro1)){
          JOptionPane.showMessageDialog(null, "Encuentro agregado");
      }else{
          JOptionPane.showMessageDialog(null, "Encuentro no agregado");
      }
        
        
    }
    
    private void asignarResultado(int r1,int r2){
        
        this.encuentro1.asignarResultado(r1, r2);
    }
    
    private boolean asignarGolLocal(Equipo e1){
        boolean result=false;
        
        
        Jugador j1;
        
            j1 = this.equipo1.getJugador((String)this.cbConvocados1.getSelectedItem());
            
           // Convocado c = this.equipo1.obtenerPlantel(jornada).obtenerConvocadoPorNombre((String)this.cbConvocados1.getSelectedItem());
            
            
          
            
            if(this.encuentro1.AsignarGolLocal(new Gol(
                    new TipoDeGol(this.cbTipogGolLocal.getSelectedItem().toString(),this.spMinutos1.getValue().toString())), j1.getConvocado())){
             
             this.limpiarTxtArea(1);
             
             this.mostrarTxtAreas(1);
                
                result=true;
            }else{
              JOptionPane.showMessageDialog(this, "max goles: "+this.spGolesLocal.getValue().toString());
          } 
            
        
           
           
        
        
        return result;
    }
    
        private boolean asignarGolVisitante(Equipo e1){
        boolean result=false;
       
        boolean b=false;
        
        Jugador j2;
        
           
            
        
            j2 = this.equipo2.getJugador((String)this.cbConvocados2.getSelectedItem());
           
          //   Convocado c2 = this.equipo2.obtenerPlantel(jornada).obtenerConvocadoPorNombre((String)this.cbConvocados2.getSelectedItem());
            
            
          if(this.encuentro1.AsignarGolVisitante(new Gol(
                  new TipoDeGol(this.cbTipoGolVisitante.getSelectedItem().toString(),this.spMinutos2.getValue().toString())), j2.getConvocado())){
              
              this.limpiarTxtArea(2);
              this.mostrarTxtAreas(2);
              result=true;
          }else{
              JOptionPane.showMessageDialog(this, "max goles: "+this.spGolesVisitante.getValue().toString());
          }  
            
         
        
        
        return result;
    }
        
        
   private void mostrarTxtAreas(int i){
       try {
             if(i==1){
          this.txtaLocal.append(this.equipo1.obtenerPlantel(jornada).mostrarGoleadoresArea()); 
       }else{
           this.txtaVisitante.append(this.equipo2.obtenerPlantel(jornada).mostrarGoleadoresArea());
       }
       
           
       } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Asigne resultado");
       }
       
     
       
       
   }    
        
   private void limpiarTxtArea(int i){
       if(i==1){
         this.txtaLocal.setText("");
       }else{
           this.txtaVisitante.setText("");
       }
       
       
   }     
   
   private void mostrarTiTuloJornada(){
       
       String texto="";
        if(jornada<Configuracion.equipos.cantidadDeEquipos()){
            texto = "Apertura";
        }else{
            texto = "Clausura";
        }
        
        if(texto.equals("Apertura")){
            this.lblJornadaDeJornada.setText(texto+"-"+"Jornada "+jornada
                +" de "+((Configuracion.equipos.cantidadDeEquipos()-1)));
        }else{
             this.lblJornadaDeJornada.setText(texto+"-"+"Jornada "+(jornada-(Configuracion.equipos.cantidadDeEquipos()-1))
                +" de "+((Configuracion.equipos.cantidadDeEquipos()-1)));
        }
        
   }
   
   
   private boolean asignarMinuto(String minuto){
       boolean result=false;
       
       if(!findMinuto(minuto)){
           this.minutos.add(minuto);
           result=true;
       }
       
       return result;
   }
   
   private boolean findMinuto(String minuto){
       boolean result=false;
       
       for(String m : this.minutos){
           if(minuto.equals(m)){
               result=true;break;
           }
       }
       
       
       return result;
   }
   
   public boolean validarForm(){
       boolean result = false;
       
       if(this.jdcCalendario.getDate()==null){
           JOptionPane.showMessageDialog(this, "Asigne una Fecha de Encuentro");
       }
       
       return result;
   }
    
}
