/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Equipo;
import Entidades.Jugador;
import Entidades.Persona;
import Entidades.Ubigeo;
import Enumerados.Demarcacion;
import Enumerados.EnumPaises;
import Sistema.Configuracion;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author ACER
 */
public class FrameJugador extends javax.swing.JFrame {

    /**
     * Creates new form FrameJugador
     */
    
    
    Jugador j;
    public FrameJugador() {
        initComponents();
        this.btnModificar.setEnabled(false);
        
    }

    public FrameJugador(Jugador j){
        initComponents();
        this.j=j;
       
        this.inicializarCampos();
        this.btnAgregar.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        lblPosicionN = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtPosicion = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        cboPaises = new javax.swing.JComboBox<>();
        cboPosiciones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboDepartamentos = new javax.swing.JComboBox<>();
        cboProvincias = new javax.swing.JComboBox<>();
        cboDistritos = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNumero.setText("numero");

        lblPais.setText("Pais");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        txtPais.setEditable(false);

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        lblEdad.setText("Edad");

        lblDNI.setText("DNI");

        lblPosicionN.setText("Posicion Natural");

        lblAltura.setText("Altura");

        txtPosicion.setEditable(false);

        cboPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPaisesActionPerformed(evt);
            }
        });

        cboPosiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPosicionesActionPerformed(evt);
            }
        });

        jLabel1.setText("Departamento");

        jLabel2.setText("Provincia");

        jLabel3.setText("Distrito");

        cboDepartamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cboDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDepartamentosActionPerformed(evt);
            }
        });

        cboProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProvinciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                .addComponent(lblPais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPosicionN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblAltura)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addComponent(txtPosicion, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboPosiciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboPaises, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEdad, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cboDistritos, javax.swing.GroupLayout.Alignment.LEADING, 0, 129, Short.MAX_VALUE)
                        .addComponent(cboProvincias, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboDepartamentos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPais)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosicionN)
                    .addComponent(txtPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPosiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboDistritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnRegresar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

        
        Jugador jugador;

        try{

            if(!this.validarFormAgregar()){

            }else{
                
                Ubigeo ubigeo = (Ubigeo)this.cboDistritos.getSelectedItem();
              
                jugador = new Jugador(Integer.parseInt(this.txtNumero.getText()),
                        this.txtPais.getText(),this.txtNombre.getText(),
                        Integer.parseInt(this.txtEdad.getText()),Integer.parseInt(this.txtDNI.getText())
                        ,this.txtPosicion.getText(), Double.parseDouble(this.txtAltura.getText()),ubigeo);
                
               
                
                int confirmado = JOptionPane.showConfirmDialog(this,"¿seguro?");
                
                if(JOptionPane.OK_OPTION==confirmado){
                    
                Configuracion.personas.agregar(jugador);
                JOptionPane.showMessageDialog(this, "AGREGADO EXITOSAMENTE");
                this.limpiar();
                    
                    
                }
                
           
            }

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ERROR");
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try{
            int p =0;
            if(!this.validarFormModificar()){

            }else{
                Ubigeo ubigeo = (Ubigeo)this.cboDistritos.getSelectedItem();
                p = Configuracion.personas.posicionDeJugador(j);
                j.setNombre(this.txtNombre.getText());
                j.setPais(this.txtPais.getText());
                j.setNumero(Integer.parseInt(this.txtNumero.getText()));
                j.setEdad(Integer.parseInt(this.txtEdad.getText()));
                j.setDni(Integer.parseInt(this.txtDNI.getText()));
                j.setPosicionJ(this.txtPosicion.getText());
                j.setAltura(Double.parseDouble(this.txtAltura.getText()));
                j.setUbigeo(ubigeo);
                Configuracion.personas.getPersonas().set(p, j);
                JOptionPane.showMessageDialog(this, "MODIFICADO EXITOSO");

                FrameGestionPersonas frm = new FrameGestionPersonas();
                frm.setLocationRelativeTo(null);
                frm.setVisible(true);
                this.dispose();
            }

        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this,"ERROR: "+e);
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
       
        this.dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cboPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPaisesActionPerformed
        // TODO add your handling code here:
        String equipo = (String)this.cboPaises.getSelectedItem();
        this.txtPais.setText(equipo);
    }//GEN-LAST:event_cboPaisesActionPerformed

    private void cboPosicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPosicionesActionPerformed
        // TODO add your handling code here:
        String posicion = (String)this.cboPosiciones.getSelectedItem();
        this.txtPosicion.setText(posicion);
    }//GEN-LAST:event_cboPosicionesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         this.cargarComboBox(); //carga los PAISES Y DEMARCACIONES
        
        ArrayList<Ubigeo> departamentos = Configuracion.peru.getDepartamentos();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(Ubigeo  u: departamentos){
            model.addElement(u);
        }
        this.cboDepartamentos.setModel(model);
        
    }//GEN-LAST:event_formWindowOpened

    private void cboDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDepartamentosActionPerformed
        // TODO add your handling code here:
        Ubigeo depart =  (Ubigeo)this.cboDepartamentos.getSelectedItem();
        
        ArrayList<Ubigeo> provincias = Configuracion.peru.getProvincias( depart.getCodUbigueo());
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(Ubigeo  u: provincias){
            model.addElement(u);
        }
        this.cboProvincias.setModel(model);
        this.cboProvinciasActionPerformed(evt);
    }//GEN-LAST:event_cboDepartamentosActionPerformed

    private void cboProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProvinciasActionPerformed
        // TODO add your handling code here:
          Ubigeo depart =  (Ubigeo)this.cboDepartamentos.getSelectedItem();
        Ubigeo provin =  (Ubigeo)this.cboProvincias.getSelectedItem();
        ArrayList<Ubigeo> distritos = Configuracion.peru.getDistritos(
            depart.getCodUbigueo(),
            provin.getCodUbigueo() );

        ArrayList<Ubigeo> dist = Configuracion.peru.getDistritos(provin);
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(Ubigeo  obj:distritos){
            model.addElement(obj);
        }
        this.cboDistritos.setModel(model);
    }//GEN-LAST:event_cboProvinciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboDepartamentos;
    private javax.swing.JComboBox<String> cboDistritos;
    private javax.swing.JComboBox<String> cboPaises;
    private javax.swing.JComboBox<String> cboPosiciones;
    private javax.swing.JComboBox<String> cboProvincias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPosicionN;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPosicion;
    // End of variables declaration//GEN-END:variables

    
public void inicializarCampos(){
        
        this.txtAltura.setText(String.valueOf(j.getAltura()));
        this.txtDNI.setText(String.valueOf(j.getDni()));
        this.txtEdad.setText(String.valueOf(j.getEdad()));
        this.txtNombre.setText(j.getNombre());
        this.txtNumero.setText(String.valueOf(j.getEdad()));
        this.txtPais.setText(j.getPais());
        this.txtPosicion.setText(String.valueOf(j.getPosicionJ()));
       // this.cboDepartamentos.setSelectedItem(j.getUbigeo());
        
    }    
     
private void limpiar(){
    
   // this.txtAltura.setText("");
    //this.txtDNI.setText("");
    this.txtEdad.setText("");
    this.txtNombre.setText("");
    this.txtNumero.setText("");
    this.txtPais.setText("");
    this.txtPosicion.setText("");
    
}

private boolean validarFormAgregar(){
        boolean result = false;
        if(this.txtNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NOMBRE DEL JUGADOR", "NOMBRE", ERROR_MESSAGE);
        
        }else if(Configuracion.personas.buscarJugadorPorNombre(this.txtNombre.getText())!=null){
            JOptionPane.showMessageDialog(this, "EL JUGADOR YA EXISTE", "NOMBRE",ERROR_MESSAGE);
            
        }else if(this.txtAltura.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA LA ALTURA", "ALTURA", ERROR_MESSAGE);
        }else if(this.txtDNI.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL DNI", "DNI", ERROR_MESSAGE);
        }else if(Configuracion.personas.buscarJugadorPorDni(Integer.parseInt(txtDNI.getText()))!=null){
            JOptionPane.showMessageDialog(this, "DNI YA REGISTRADO ", "DNI", ERROR_MESSAGE);
        }
        else if(this.txtEdad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA LA EDAD", "EDAD", ERROR_MESSAGE);
        }else if(this.txtNumero.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NUMERO", "NUMERO", ERROR_MESSAGE);
        }else if(this.txtPais.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL PAIS", "PAIS", ERROR_MESSAGE);
        }else if(this.txtPosicion.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA POSICION", "POSICION", ERROR_MESSAGE);
        }else if(this.cboDistritos.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "ELIGA DISTRITO", "DISTRITO", ERROR_MESSAGE);
        }
        
        else{
            result = true;
        }
        return result;     
    } 




 private boolean validarFormModificar(){
         boolean result = false;
        if(this.txtNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NOMBRE DEL JUGADOR", "NOMBRE", ERROR_MESSAGE);
        }else if(this.txtAltura.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA LA ALTURA", "ALTURA", ERROR_MESSAGE);
        }else if(this.txtDNI.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL DNI", "DNI", ERROR_MESSAGE);
        }else if(this.txtEdad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA LA EDAD", "EDAD", ERROR_MESSAGE);
        }else if(this.txtNumero.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL NUMERO", "NUMERO", ERROR_MESSAGE);
        }else if(this.txtPais.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL PAIS", "PAIS", ERROR_MESSAGE);
        }else if(this.txtPosicion.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA POSICION", "POSICION", ERROR_MESSAGE);
        }else{
            if(this.validarModificacion()){
                
             result = true;   
             
            }
        }
        return result;     
    } 

 
     private boolean validarModificacion(){
         boolean result=true;
         
          if(!this.txtNombre.getText().equals(this.j.getNombre())){
            if(Configuracion.personas.buscarJugadorPorNombre(this.txtNombre.getText())!=null){
              JOptionPane.showMessageDialog(this, "EL NOMBRE YA EXISTE", "NOMBRE",ERROR_MESSAGE);
              result=false;  
            }
            
          }else if(!this.txtDNI.getText().equals(String.valueOf(j.getDni()))){
              if(Configuracion.personas.buscarJugadorPorDni(Integer.parseInt(this.txtDNI.getText()))!=null){
                 JOptionPane.showMessageDialog(this, "DNI YA REGISTRADO", "DNI", ERROR_MESSAGE);
                 result=false; 
              }
              
               
          }
         
         return result;
     }
 
 
     
     private void cargarComboBox(){
         
         for(int i=0;i<EnumPaises.values().length;i++){
             
             this.cboPaises.addItem(EnumPaises.values()[i].name());
         }
         
         for(int i=0;i<Demarcacion.values().length;i++){
             
             this.cboPosiciones.addItem(Demarcacion.values()[i].name());
         }
         
         
     }
     
     
     
}

