/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Encuentro;
import Entidades.Fecha;
import Sistema.Configuracion;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FrameListaEncuentros extends javax.swing.JFrame {

    /**
     * Creates new form FrameListaEncuentros
     */
    
    Fecha f;
    int xd;
    public FrameListaEncuentros(){
        initComponents();
        this.cargarcomboBox();
        xd=2;
        
    }

     public FrameListaEncuentros(int i){
        initComponents();
        
        this.cargarTabla(i);
        
        this.cbJornadas.setEnabled(false);
        this.cbJornadas2.setEnabled(false);
        this.rbApertura.setEnabled(false);
        this.rbClausura.setEnabled(false);
        xd=1;
    }
    
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnRegresar = new javax.swing.JButton();
        cbJornadas = new javax.swing.JComboBox<>();
        cbJornadas2 = new javax.swing.JComboBox<>();
        rbApertura = new javax.swing.JRadioButton();
        rbClausura = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultadosEncuentros = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FIXTURE");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setText("regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, -1, -1));

        cbJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJornadasActionPerformed(evt);
            }
        });
        getContentPane().add(cbJornadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 105, -1));

        cbJornadas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJornadas2ActionPerformed(evt);
            }
        });
        getContentPane().add(cbJornadas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 105, -1));

        buttonGroup1.add(rbApertura);
        rbApertura.setText("Apertura");
        rbApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAperturaActionPerformed(evt);
            }
        });
        getContentPane().add(rbApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, -1, -1));

        buttonGroup1.add(rbClausura);
        rbClausura.setText("Clausura");
        rbClausura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClausuraActionPerformed(evt);
            }
        });
        getContentPane().add(rbClausura, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, -1, -1));

        tblResultadosEncuentros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResultadosEncuentros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultadosEncuentrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultadosEncuentros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 730, 420));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Haga Click para ver los resultados");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/resultados.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
        if(xd==1){
           FrameGestionJornadas frm = new FrameGestionJornadas();
            frm.setLocationRelativeTo(null);
                frm.setVisible(true);
            this.dispose(); 
        }else if(xd==2){
           this.dispose();
        }
        
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tblResultadosEncuentrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultadosEncuentrosMouseClicked
        // TODO add your handling code here:
        
        try {
            int columna=6;
            int fila=0;
            String id="";
             fila = this.tblResultadosEncuentros.getSelectedRow();
             
             id = (String)this.tblResultadosEncuentros.getValueAt(fila, 6);
             
             Encuentro e = f.obtenerEncuentro(id);
             
             //JOptionPane.showMessageDialog(this, e.mostrarResultado());
             JTextArea textArea = new JTextArea(e.mostrarResultado());
            JScrollPane scrollPane = new JScrollPane(textArea);  
            textArea.setLineWrap(true);  
            textArea.setWrapStyleWord(true); 
            scrollPane.setPreferredSize( new Dimension( 500, 500 ) );
            JOptionPane.showMessageDialog(null, scrollPane, "ESTADISTICAS",  
                                       JOptionPane.YES_NO_OPTION);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:"+e);
        }
        
    }//GEN-LAST:event_tblResultadosEncuentrosMouseClicked

    private void rbAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAperturaActionPerformed
        // TODO add your handling code here:
        this.cbJornadas.setEnabled(true);
        this.cbJornadas2.setEnabled(false);
        cbJornadasActionPerformed(evt);
    }//GEN-LAST:event_rbAperturaActionPerformed

    private void cbJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJornadasActionPerformed
        // TODO add your handling code here:
         this.cargarTabla(this.cbJornadas.getSelectedIndex());
    }//GEN-LAST:event_cbJornadasActionPerformed

    private void cbJornadas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJornadas2ActionPerformed
        // TODO add your handling code here:
        this.cargarTabla(this.cbJornadas2.getSelectedIndex()+Configuracion.equipos.cantidadDeEquipos()-1);
    }//GEN-LAST:event_cbJornadas2ActionPerformed

    private void rbClausuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClausuraActionPerformed
        // TODO add your handling code here:
         this.cbJornadas.setEnabled(false);
        this.cbJornadas2.setEnabled(true);
        cbJornadas2ActionPerformed(evt);
    }//GEN-LAST:event_rbClausuraActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:        this.cargarcomboBox();
      
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameListaEncuentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameListaEncuentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameListaEncuentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameListaEncuentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameListaEncuentros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbJornadas;
    private javax.swing.JComboBox<String> cbJornadas2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbApertura;
    private javax.swing.JRadioButton rbClausura;
    private javax.swing.JTable tblResultadosEncuentros;
    // End of variables declaration//GEN-END:variables

    private void cargarcomboBox(){
        
         for(int i=0;i<Configuracion.equipos.cantidadDeEquipos()-1;i++){
            
            this.cbJornadas.addItem("Jornada "+(i+1));
            
        }
         
        for(int j=Configuracion.equipos.cantidadDeEquipos()-1;j<2*(Configuracion.equipos.cantidadDeEquipos()-1);j++){
            
            this.cbJornadas2.addItem("Jornada "+(j+1));
        } 
    }
    
    private void cargarTabla(int i){
        
        
        f= Configuracion.fechas.obtenerFechaPorJornada(i+1);
        
        if(f!=null){
           DefaultTableModel tabla = new DefaultTableModel(f.getMatrizResultadoEncuentros(),f.titulosEncuentros());
        this.tblResultadosEncuentros.setModel(tabla);
         
        this.tblResultadosEncuentros.setRowHeight(30);
        }
       
    }
    
}
