/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Calendario.Calendario;
import Entidades.Equipo;
import Sistema.Configuracion;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FrameGanador extends javax.swing.JFrame {

    /**
     * Creates new form FrameGanador
     */
    
    
    String[] matriz = new String[2];
    Equipo mayor;
    Equipo menor ;
    Equipo equipo;
    boolean ganador;
    public FrameGanador() {
        initComponents();
        
        this.ganador();
        this.cargarComboBox();
        this.cargarNombre();
        JOptionPane.showMessageDialog(this,"FINALISTAS: \n"
                + "- "+matriz[0]+" \n"
                +"- "+matriz[1]);
        
        
        
       /* if(e!=null){
             this.txtGanador.setText(e.getNombre());
        }*/
      
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGanador = new javax.swing.JTextField();
        lblCopa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFinal = new javax.swing.JTable();
        combo = new javax.swing.JComboBox<>();
        panEmpate = new javax.swing.JPanel();
        lblVisitante3 = new javax.swing.JLabel();
        spLocal3 = new javax.swing.JSpinner();
        spVuelta3 = new javax.swing.JSpinner();
        lblLocal3 = new javax.swing.JLabel();
        panIda1 = new javax.swing.JPanel();
        lblVisitante1 = new javax.swing.JLabel();
        spLocal1 = new javax.swing.JSpinner();
        spVuelta1 = new javax.swing.JSpinner();
        lblLocal1 = new javax.swing.JLabel();
        panVuelta = new javax.swing.JPanel();
        lblVisitante2 = new javax.swing.JLabel();
        spLocal2 = new javax.swing.JSpinner();
        spVuelta2 = new javax.swing.JSpinner();
        lblLocal2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GANADOR LIGA 1");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGanador.setEditable(false);
        txtGanador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtGanador.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(txtGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 190, 40));

        lblCopa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copa.png"))); // NOI18N
        lblCopa.setText("jLabel1");
        getContentPane().add(lblCopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 220, 330));

        tablaFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaFinal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 230));

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, -1));

        panEmpate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVisitante3.setBackground(new java.awt.Color(255, 255, 255));
        lblVisitante3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        panEmpate.add(lblVisitante3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 110, 20));

        spLocal3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        panEmpate.add(spLocal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        spVuelta3.setModel(new javax.swing.SpinnerNumberModel(0, null, 10, 1));
        panEmpate.add(spVuelta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 40, -1));

        lblLocal3.setBackground(new java.awt.Color(255, 255, 255));
        lblLocal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        panEmpate.add(lblLocal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        getContentPane().add(panEmpate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 340, 40));

        panIda1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVisitante1.setBackground(new java.awt.Color(255, 255, 255));
        lblVisitante1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        panIda1.add(lblVisitante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 110, 20));

        spLocal1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        panIda1.add(spLocal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        spVuelta1.setModel(new javax.swing.SpinnerNumberModel(0, null, 10, 1));
        panIda1.add(spVuelta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 40, -1));

        lblLocal1.setBackground(new java.awt.Color(255, 255, 255));
        lblLocal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        panIda1.add(lblLocal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        getContentPane().add(panIda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 340, 40));

        panVuelta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVisitante2.setBackground(new java.awt.Color(255, 255, 255));
        lblVisitante2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        panVuelta.add(lblVisitante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 110, 20));

        spLocal2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        panVuelta.add(spLocal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        spVuelta2.setModel(new javax.swing.SpinnerNumberModel(0, null, 10, 1));
        panVuelta.add(spVuelta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 40, -1));

        lblLocal2.setBackground(new java.awt.Color(255, 255, 255));
        lblLocal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        panVuelta.add(lblLocal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        getContentPane().add(panVuelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 340, 40));

        jButton1.setText("GENERAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        jLabel1.setText("GANADOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 70, -1));

        jLabel2.setText("IDA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 30, 20));

        jLabel3.setText("IDA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 30, 20));

        jLabel4.setText("VUELTA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
        if(this.combo.getSelectedIndex()==0){
            this.cargarTablaIda();
            this.panIda1.setVisible(true);
            this.panVuelta.setVisible(false);
            this.panEmpate.setVisible(false);
        }else if(this.combo.getSelectedIndex()==1){
            this.cargarTablaVuelta();
            this.panIda1.setVisible(false);
            this.panVuelta.setVisible(true);
            this.panEmpate.setVisible(false);
        }
    }//GEN-LAST:event_comboActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        this.panIda1.setVisible(false);
        this.panVuelta.setVisible(false);
        this.panEmpate.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!this.panEmpate.isVisible()){
           this.generarGanador();
           
       }else{
            this.generarGanadorExtra();
            
        }
        
        
        
        if(ganador){
            JOptionPane.showMessageDialog(this,"GANADOR DEL TORNEO "+ equipo);
            this.txtGanador.setText(equipo.getNombre());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGanador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCopa;
    private javax.swing.JLabel lblLocal1;
    private javax.swing.JLabel lblLocal2;
    private javax.swing.JLabel lblLocal3;
    private javax.swing.JLabel lblVisitante1;
    private javax.swing.JLabel lblVisitante2;
    private javax.swing.JLabel lblVisitante3;
    private javax.swing.JPanel panEmpate;
    private javax.swing.JPanel panIda1;
    private javax.swing.JPanel panVuelta;
    private javax.swing.JSpinner spLocal1;
    private javax.swing.JSpinner spLocal2;
    private javax.swing.JSpinner spLocal3;
    private javax.swing.JSpinner spVuelta1;
    private javax.swing.JSpinner spVuelta2;
    private javax.swing.JSpinner spVuelta3;
    private javax.swing.JTable tablaFinal;
    private javax.swing.JTextField txtGanador;
    // End of variables declaration//GEN-END:variables

    
    private void ganador(){
   
        try {
            
              JOptionPane.showMessageDialog(this,"GENERANDO GANADOR..: "+
                Configuracion.equipos.getEquipos().size()+" CLUBES  ");
     
        
        ArrayList<Equipo> equipos = Configuracion.equipos.getEquipos();
         ArrayList<Equipo> equiposCopia = new ArrayList<Equipo>(equipos);
        Collections.sort(equiposCopia,Collections.reverseOrder());
        
        mayor = equiposCopia.get(0);
        menor = equiposCopia.get(1);
        
        matriz[0] = mayor.getNombre();
        matriz[1] = menor.getNombre();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e);
        }
        
      
        
    }
    
    public String[] cabeceraEncuentros(){
            
            String[] result = new String[4];
            
            result[0] = "LOCAL";
            result[1] = "g";
            result[2] = "g";
            result[3] = "VISITANTE";
            
            return result;
        }
    
     public String[][] getMatrizEncuentrosIda(){
            
            String[][] result=new String[1][4];
           
            int i=0;
               
                        result[i][0] = this.matriz[0];
                        result[i][1] = " ";
                        result[i][2] = " ";
                        result[i][3] = this.matriz[1];
                        i++;
                      
                
            return result;
            
        }
    
     public String[][] getMatrizEncuentrosVuelta(){
            
            String[][] result=new String[1][4];
           
            int i=0;
               
                        result[i][0] = this.matriz[1];
                        result[i][1] = " ";
                        result[i][2] = " ";
                        result[i][3] = this.matriz[0];
                        i++;
                      
                
            return result;
            
        }
     
     private void cargarTablaIda(){
        
      
         try {
             
             DefaultTableModel table = new DefaultTableModel(this.getMatrizEncuentrosIda(),
                this.cabeceraEncuentros());
       
     
        this.tablaFinal.setModel(table);
     
       this.tablaFinal.setRowHeight(50);
       this.tablaFinal.getColumnModel().getColumn(0).setPreferredWidth(200);
       this.tablaFinal.getColumnModel().getColumn(1).setPreferredWidth(5);
       this.tablaFinal.getColumnModel().getColumn(2).setPreferredWidth(5);
       this.tablaFinal.getColumnModel().getColumn(3).setPreferredWidth(200);
             
             
         } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "ERROR: "+e);
         }
       
       
    }
    
      private void cargarTablaVuelta(){
        
          try {
              
               
       DefaultTableModel table = new DefaultTableModel(this.getMatrizEncuentrosVuelta(),
                this.cabeceraEncuentros());
       
        this.tablaFinal.setModel(table);
      
       this.tablaFinal.setRowHeight(50);
       this.tablaFinal.getColumnModel().getColumn(0).setPreferredWidth(200);
       this.tablaFinal.getColumnModel().getColumn(1).setPreferredWidth(5);
       this.tablaFinal.getColumnModel().getColumn(2).setPreferredWidth(5);
       this.tablaFinal.getColumnModel().getColumn(3).setPreferredWidth(200);
              
      
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "ERROR: "+e);
          }
  
      
    }
     
     private void cargarComboBox(){
         
         this.combo.addItem("IDA");
         this.combo.addItem("VUELTA");
         
     }
     
          
     private void cargarNombre(){
         this.lblLocal1.setText(matriz[0]);
         this.lblLocal2.setText(matriz[0]);
         this.lblLocal3.setText(matriz[0]);
         
         this.lblVisitante1.setText(matriz[1]);
         this.lblVisitante2.setText(matriz[1]);
         this.lblVisitante3.setText(matriz[1]);
         
     }
     
     private void generarGanador(){
         ganador=false;
         boolean g=false;
         int golesLocal =(int) this.spLocal1.getValue() + (int) this.spLocal2.getValue();
         int golesVisitante = (int) this.spVuelta1.getValue() + (int) this.spVuelta2.getValue() ;
         
         if(golesLocal>golesVisitante){
             this.equipo= mayor;
             ganador=true;
         }else if(golesLocal<golesVisitante){
             this.equipo=menor;
             ganador=true;
         }else{
             JOptionPane.showMessageDialog(this, "3er PARTIDO");
             g=true;
         }
         
         if(g){
             
             this.panIda1.setVisible(false);
             this.panVuelta.setVisible(false);
             this.panEmpate.setVisible(true);
             this.combo.setEnabled(false);
             ganador=false;
         }
         
     }
     
     private void generarGanadorExtra(){
         
         
         boolean g=false;
         int golesLocal =(int) this.spLocal3.getValue();
         int golesVisitante = (int) this.spVuelta3.getValue();
         
         if(golesLocal>golesVisitante){
             this.equipo= mayor;
             ganador=true;
         }else if(golesLocal<golesVisitante){
             this.equipo=menor;
             ganador=true;
         }else{
             g=true;
             JOptionPane.showMessageDialog(this, "PENALES");
         }
         
         if(g){
             this.panIda1.setEnabled(false);
             this.panVuelta.setEnabled(false);
             this.panEmpate.setEnabled(true);
             ganador=false;
         }
         
         
     }
     
     
   }
    
     
    
    

